In [2]:
# Imports
import os
import numpy as np
import pandas as pd
import mne
import matplotlib.pyplot as plt
import random
import math
%matplotlib inline

In [3]:
def read_labels(file_path):
    label_df = pd.read_csv(file_path)
    data = label_df[['No.', 'label']]
    data = data.to_numpy()
    dict_label = dict()

    for i in range(len(data)):
        dict_label[data[i][0]] = data[i][1]
    return dict_label

label_file_path = '../data/label_jo/PSS.csv'
dict_label = read_labels(label_file_path)    
print(dict_label)

{1: 0, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 0, 10: 1, 11: 0, 12: 0, 13: 1, 14: 0, 15: 0, 16: 1, 17: 0, 18: 0, 19: 0, 20: 0, 21: 1, 22: 0, 23: 1, 24: 1, 25: 0, 26: 1, 27: 0, 28: 0, 29: 1, 30: 0, 31: 0, 32: 1, 33: 0, 34: 1, 35: 0, 36: 1, 37: 1, 38: 1, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 1, 45: 1, 46: 0, 47: 0, 48: 0, 49: 1, 50: 0, 51: 1, 52: 1, 53: 0, 54: 1, 55: 0}


In [4]:
def group_participants(dict_label):
    non_stressed = []
    stressed = []
    
    for key in dict_label:
        if dict_label[key] == 1:
            stressed.append(key)
        else:
            non_stressed.append(key)
    return non_stressed, stressed

non_stressed, stressed = group_participants(dict_label)    
non_stressed = np.array(non_stressed)
stressed = np.array(stressed)
non_stressed, stressed

(array([ 1,  9, 11, 12, 14, 15, 17, 18, 19, 20, 22, 25, 27, 28, 30, 31, 33,
        35, 39, 41, 42, 46, 47, 48, 50, 53, 55]),
 array([ 2,  3,  4,  5,  6,  7,  8, 10, 13, 16, 21, 23, 24, 26, 29, 32, 34,
        36, 37, 38, 40, 43, 44, 45, 49, 51, 52, 54]))

In [5]:
random.seed(999)
random.shuffle(non_stressed)
random.shuffle(stressed)

In [6]:
non_stressed

array([19, 55, 15,  9, 18, 30, 25, 27, 33, 41, 28,  1, 20, 47, 50, 17, 12,
       22, 14, 42, 31, 35, 48, 39, 11, 46, 53])

In [7]:
stressed

array([49, 34, 16, 26, 45, 10, 13, 37,  8, 24, 51,  3,  5, 44, 52,  2, 40,
       32,  6, 23, 29, 38, 36,  4, 54, 21, 43,  7])

In [10]:
non_stressed.shape, stressed.shape

((27,), (28,))

In [9]:
percent_train = .8

m_ns_train = int(math.ceil(non_stressed.shape[0] * percent_train))
m_s_train = int(math.ceil(stressed.shape[0] * percent_train))

m_ns_train, m_s_train

(22, 23)

In [11]:
non_stressed_train = non_stressed[:m_ns_train]
non_stressed_test = non_stressed[m_ns_train:]
non_stressed_train, non_stressed_test

(array([19, 55, 15,  9, 18, 30, 25, 27, 33, 41, 28,  1, 20, 47, 50, 17, 12,
        22, 14, 42, 31, 35]),
 array([48, 39, 11, 46, 53]))

In [13]:
non_stressed_train.shape, non_stressed_test.shape

((22,), (5,))

In [14]:
stressed_train = stressed[:m_s_train]
stressed_test = stressed[m_s_train:]
stressed_train, stressed_test

(array([49, 34, 16, 26, 45, 10, 13, 37,  8, 24, 51,  3,  5, 44, 52,  2, 40,
        32,  6, 23, 29, 38, 36]),
 array([ 4, 54, 21, 43,  7]))

In [15]:
stressed_train.shape, stressed_test.shape

((23,), (5,))

In [17]:
train_participants = np.concatenate((non_stressed_train, stressed_train))
train_participants

array([19, 55, 15,  9, 18, 30, 25, 27, 33, 41, 28,  1, 20, 47, 50, 17, 12,
       22, 14, 42, 31, 35, 49, 34, 16, 26, 45, 10, 13, 37,  8, 24, 51,  3,
        5, 44, 52,  2, 40, 32,  6, 23, 29, 38, 36])

In [18]:
train_participants.shape

(45,)

In [19]:
test_participants = np.concatenate((non_stressed_test, stressed_test))
test_participants

array([48, 39, 11, 46, 53,  4, 54, 21, 43,  7])

In [20]:
test_participants.shape

(10,)