In [31]:
# Imports
import os
import numpy as np
import pandas as pd
import mne
import matplotlib.pyplot as plt
import random
import math
%matplotlib inline

In [32]:
def read_labels(file_path):
    label_df = pd.read_csv(file_path)
    data = label_df[['id', 'label']]
    data = data.to_numpy()
    non_stressed = []
    stressed = []

    for i in range(len(data)):
        if data[i][1] == 1:
            stressed.append(data[i][0])
        else:
            non_stressed.append(data[i][0])
    return non_stressed, stressed

label_file_path = '../data/labels/PSS10-Sheet1.csv'
non_stressed, stressed = read_labels(label_file_path)    
non_stressed = np.array(non_stressed)
stressed = np.array(stressed)
non_stressed, stressed

(array([ 4,  5,  6,  7,  9, 10, 11, 13, 14, 15]),
 array([ 1,  2,  3,  8, 12, 16, 17]))

In [33]:
random.seed(999)
random.shuffle(non_stressed)
random.shuffle(stressed)

In [34]:
non_stressed

array([10, 11,  9,  4,  6, 15,  7, 13, 14,  5])

In [35]:
stressed

array([ 8, 17, 16,  1, 12,  3,  2])

In [36]:
percent_train = .8

m_ns_train = int(non_stressed.shape[0] * percent_train)
m_s_train = int(math.ceil(stressed.shape[0] * percent_train))

m_ns_train, m_s_train

(8, 6)

In [37]:
non_stressed_train = non_stressed[:m_ns_train]
non_stressed_test = non_stressed[m_ns_train:]
non_stressed_train, non_stressed_test

(array([10, 11,  9,  4,  6, 15,  7, 13]), array([14,  5]))

In [38]:
stressed_train = stressed[:m_s_train]
stressed_test = stressed[m_s_train:]
stressed_train, stressed_test

(array([ 8, 17, 16,  1, 12,  3]), array([2]))